sudo: required

language: java

jdk: oraclejdk8

services:
  - docker

addons:
  apt:
    packages:
      - oracle-java8-installer

install: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew build bintrayUpload buildDockerImageTagLatest buildDockerImageTagVersion -PbintrayUser=${BINTRAY_USER} -PbintrayApiKey=${BINTRAY_API_KEY} -Pbranch=${TRAVIS_BRANCH} -PbuildNumber=${TRAVIS_BUILD_NUMBER}

after_success:
  - bash <(curl -s https://codecov.io/bash)
