version: '2'
services:
  mariadb:
    image: 'soen387fall2016/erm-dataservice-db'
    volumes:
      - ../erm-dataservice-sql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  server:
    image: 'soen387fall2016/erm-dataservice-server'
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    links:
      - mariadb
    depends_on:
      - mariadb
